### ISSUE TITLE
Does not support YAML 1.2 as stated.

### ISSUE THREAD

**Issue by softlion** [xoofx/SharpYaml#23]

**Comment by xoofx** [comment]
It is not stated that it supports 1.2. It is stated that it supports YAML schema from 1.2 and I'm not even sure it supports the whole stuff...

That being said, whenever you open an issue, please take the time to fill a bit more details instead of throwing just a "does not work as expected" in the title, without any details in the description... That's an incredibly disrespectful way to interact with an OSS project...

**Comment by softlion** [comment]
The header of the schema is tested with 1.1 explicitely in the code.
So if you have 1.2 set it just crash.

**Comment by xoofx** [comment]
I haven't touch this code base for months, and I barely have spare time to spent digging into this issue, or even fix it, but mind a link to `with 1.1 explicitely in the code.`? so that if you want to fix it in a PR, or someone else, it will be welcome.

**Comment by softlion** [comment]
Btw yaml is fading away, why bother.

**Comment by xoofx** [comment]
> Btw yaml is fading away, why bother

So why opening this issue in the first place then?

You are right that I have little incentive to maintain this project. But the way you are interacting here is just disconcerting. So yeah, why bother...
