### ISSUE TITLE
ObjectFactory and Unity

### ISSUE THREAD

**Issue by CompleteBrains** [xoofx/SharpYaml#6]
Hello.

#### Question: 1
I want that all my objects from a YAML file will be resolved through Unity container. I have chosen the `SerializerSettings.ObjectFactory` approach because I don’t want to manually register my custom serializer for each type in the YAML file (there are a lot of types).

```C#
settings.ObjectFactory = new LambdaObjectFactory (type => Unity.Resolve (type),
 new DefaultObjectFactory ());
```

But my factory is called for all objects from YAML, even for `List<>`. Surely I can register `List<>` in Unity to resolve it. But I think I’ve missed some better solution.

#### Question: 2
If I resolve from Unity class `Car`:
```C#
class Car
{
   public Door Left;

   public (Door left) 
   {
        this.Left = left;
   }
}

class Door
{
   public string Color;
}
``` 
The field of type `Door` will be resolved too so the memory for it will be allocated.
However the YAML parser will create the `Door` object again during deserialization `serializer.Deserialize<Car>` the file:
```YAML
Left: 
  Color: Red
```
Can I configure such things?

Also I can assume that *Deserialization* term means that all objects are created only during deserialization process and not otherwise. But how can I use Unity in this case?

**Comment by xoofx** [comment]
Hi,
Sorry to get back to you only now. You are probably away from this problem now...
But for question 1), hm, not sure to understand, either you need to handle it in your `Unity.Resolve` either the `DefaultObjectFactory` called otherwise is fine.
For Q2) The code you posted is not likely to work (Car mush have a public default parameterless constructor). Latest version of SharpYaml is also trying to use an existing instance member before trying to instantiate it.

**Comment by CompleteBrains** [comment]
Thank you for Q1.

> Latest version of SharpYaml is also trying to use an existing instance member before trying to instantiate it.

Yes, I see new commits now. 

Also, thanks for the SharpYaml, I like to work with it.
