### ISSUE TITLE
Yaml creation error

### ISSUE THREAD

**Issue by liuyl1992** [xoofx/SharpYaml#73]
![image](https://user-images.githubusercontent.com/16396828/72600641-03f7ea00-394f-11ea-9637-7b02c4083451.png)
result：
![image](https://user-images.githubusercontent.com/16396828/72600665-0eb27f00-394f-11ea-94c7-c9c2368fdb26.png)

**Comment by limeschool** [comment]
I have a similar issue. No clue how to resolve it, and it's seriously harming development.

**Comment by limeschool** [comment]
I've tracked this down to [AnchorSerializer.cs](https://github.com/xoofx/SharpYaml/blob/4f52435c49f70259ccb31c53a484f14d071f6024/SharpYaml/Serialization/Serializers/AnchorSerializer.cs). Disabling anchoring and aliases would resolve this issue, yet I cannot find any documentation on how to do this.

**Comment by limeschool** [comment]
[YamlSharp.Serializer.Settings](https://github.com/xoofx/SharpYaml/blob/4f52435c49f70259ccb31c53a484f14d071f6024/SharpYaml/Serialization/SerializerSettings.cs).EmitAlias is set to 'true' by default. I thought setting it to 'false' would disable this behavior, but rather, it increased it. Now, every variable was given an anchor tag, due to the fact that aliases (but no anchors) were now disabled. @xoofx, is there really no way to outright disable outputting anchors?

**Comment by limeschool** [comment]
Issue #15 ("How do I get Serialize() to stop putting out anchor and reference labels?") was about this same thing, actually, and the response of setting 'SortKeyForMapping' and 'EmitAlias' both to false before serializing simply does not resolve this (at least not anymore). For now, switching to JSON over YAML seems like a good option due to readability concerns.

**Comment by xoofx** [comment]
You have to use `SerializerSettings` and disable aliasing.

```c#
using System;
using SharpYaml.Serialization;

namespace SharpYaml.Tests
{
    internal class Program
    {
        public static void Main(string[] args)
        {
            var settings = new SerializerSettings {EmitAlias = false};
            var serializer = new Serializer(settings);
            var tester = new Tester() { A = "this is a", B = "this is a"};
            var text = serializer.Serialize(tester);
            Console.WriteLine(text);
        }

        public struct Tester
        {
            public string A { get; set; }

            public string B { get; set; }
        }
    }
}
```
